name: run and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
     

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
#     needs: [build]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd DidIAsk-rs/
          git pull
          export PATH=$PATH:$HOME/.cargo/bin
          ./build.sh
          killall DidIAsk
          mv target/release/DidIAsk ~/run/DidIAsk
          cd ~/run
          git pull
          ./DidIAsk </dev/null &>/dev/null &
          exit
          
